name: ezeness
description: Ezeness App .

publish_to: "none"

version: 1.0.51+61

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  compressor:
    git:
      url: https://gitlab.com/ezeness3/compressor.git
      ref: main
  media_library:
    git:
      url: https://gitlab.com/ezeness3/media_library.git
      ref: main
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.2.0
  equatable: ^2.0.3
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^17.2.2
  flutter_rounded_date_picker: ^3.0.4
  flutter_screenutil: ^5.9.0
  flutter_social_textfield: ^0.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_stripe: ^9.5.0+1
  flutter_svg: ^2.0.9
  flutter_widget_from_html: ^0.14.11
  fluttertoast: ^8.2.5
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_maps_place_picker_mb: ^3.1.2
  http: ^1.1.0
  iconly: ^1.0.1
  intl: ^0.19.0
  keep_screen_on: ^3.0.0
  media_picker_widget: ^1.0.7
  package_info_plus: null
  path_provider: ^2.1.1
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  receive_sharing_intent: ^1.8.0
  responsive_grid: ^2.4.4
  rxdart: null
  share_plus: ^10.0.0
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  timeago: ^3.6.0
  uni_links: ^0.5.1
  upgrader: ^9.0.0
  url_launcher: ^6.2.1
  video_player: ^2.8.1
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.4.0+2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  google_sign_in_ios: ^5.7.7
  fluttertagger: ^2.2.1
  dropdown_search: ^5.0.6
  video_compress: ^3.1.3
  flutter_image_compress:
dev_dependencies:
  flutter_launcher_icons: null
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  image_path_ios: "assets/images/border_icon.png"
  min_sdk_android: 21

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

flutter_intl:
  enabled: true
