name: media_library
description: A Media Library package.
version: 1.0.1
homepage: .dart_toolkit

# This package supports all platforms listed below.
platforms:
  android:
  ios:

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camerawesome: ^2.0.1
  video_player: ^2.8.7
  provider: ^6.1.2
  wechat_assets_picker: ^9.0.3
  permission_handler: ^11.3.1
  font_awesome_flutter: ^10.7.0
  image_cropper:
  video_editor: ^3.0.0
  fraction: ^5.0.2
  iconly: ^1.0.1
  compressor:
    path: ../compressor-main
#  compressor:
#    git:
#      url: https://gitlab.com/ezeness3/compressor.git
#      ref: main
  path_provider: any
  stack_board: ^0.2.4
  path: any
  image: ^4.1.4
  photo_view: ^0.15.0
  google_fonts: ^6.1.0
  image_gallery_saver: ^2.0.3
  hsv_color_pickers: ^0.3.0
  flutter_svg: ^2.0.4

  dotted_border: ^2.0.0+2
  # modal_gif_picker: ^0.0.2
  # painting
  perfect_freehand: ^2.3.0
  # positioning
  align_positioned: ^4.0.0
  #message
  # fluttertoast: ^8.1.2
  oktoast: ^3.4.0

  # animated_text_kit: ^4.2.2

  flutter_screenutil: ^5.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # assets:
  #   - assets/1.mp3
  assets:
    - assets/icons/
    - assets/icons/story.png
    - assets/stickers/
    - assets/stickers/2/
    - assets/emojies/
